export enum ACCESS_PRIVILEGE {
  READ = "READ",
  READ_ALL = "READ_ALL",
  WRITE = "WRITE",
  WRITE_ALL = "WRITE_ALL",
  DELETE = "DELETE",
  DELETE_ALL = "DELETE_ALL",
  "*" = "*",
}
export enum RESOURCE {
  AUTH = "AUTH",
  USERS = "USERS",
  ROLES = "ROLES",
  MARKETING_TARGETS = "MARKETING_TARGETS",
  CATEGORIES = "CATEGORIES",
  "*" = "*",
}
