FROM nginx
COPY ../dev-env/templates/index.html /usr/share/nginx/html/index.html
RUN apt-get update && apt-get install -y procps


# root
    ## dev-env (Folder)
        ### templates (Folder)
            #### index.html (File)
        ### docker-compose.yml (File)
    ## dockerfile (Folder)
        ### dockerfile.proxy-balancer (File)