import "@nizar-repo/tailwindcss-config/tailwind/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Wrapper from "../Wrappers";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
