FROM nginx
COPY ./dev/templates/index.html /usr/share/nginx/html/index.html
# RUN apt-get update && apt-get install -y procps

# dev
## templates
### index.html
## docker-compose.yml
# dockerfile
## dockerfile.proxy-balancer