version: "3.9"

services:
  database:
    image: mongo:7.0.5-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - nestjs_network
    ports:
      - "27017:27017"

networks:
  nestjs_network:
    driver: bridge
