name: Workflow Dispatch Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Select package to publish"
        required: true
        default: "N/A"
        type: choice
        options:
          # PACKAGES_PLACEHOLDER
      versionUpdate:
        description: "Select version update"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing ${{github.event.inputs.package_name}} with ${{github.event.inputs.versionUpdate}} version update"
