version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: ./dockerfiles/dockerfile.proxy-balancer
    image: nginx
    volumes:
      - ./templates/:/usr/share/nginx/html/main
      - ../conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80