name: Consumming variable to reuse later
on:
    workflow_dispatch:


jobs:
    consume_var:
        uses: ./.github/workflows/~template_consume_var.yml
        with:
          package_name: "@nizar-repo/error-handler"
        secrets: inherit