name: Consumming variable to reuse later

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn
      - id: get_version
        run: export app_version=$(npm pkg -w @edonec/blogs get version | head -n 1 | xargs)
      - name: Use the output
        run: |
          echo "The version is $version"
      - run: echo "Publishing @nizar-repo/error-handler with token ${{secrets.NPM_PUBLISH_TOKEN}}"
