name: Workflow Dispatch Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Select package to publish"
        required: true
        default: "N/A"
        type: choice
        options:
          - "N/A"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"

jobs:
  publish:
    uses: ./.github/workflows/~template_publish.yml
    with:
      package_name: ${{github.event.inputs.package_name}}
    secrets: inherit
  other_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        run: echo "This is another job"
  tag_workflow:
    needs:
      - publish
      - other_job
    uses: ./.github/workflows/~template_tag.yml
    with:
      package_name: ${{github.event.inputs.package_name}}
    secrets: inherit
  
  release:
    uses: ./.github/workflows/~template_release.yml
    needs: tag_workflow
    with:
      package_name: ${{github.event.inputs.package_name}}
    secrets: inherit
    