name: Workflow Dispatch Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Select package to publish"
        required: true
        default: "N/A"
        type: choice
        options:
          - "N/A"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"
      versionUpdate:
        description: "Select version update"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing ${{github.event.inputs.package_name}} with ${{github.event.inputs.versionUpdate}} version update with token ${{secrets.NPM_PUBLISH_TOKEN}}"
