name: Workflow Dispatch Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Select package to publish"
        required: true
        default: "N/A"
        type: choice
        options:
          - "N/A"
          - "@nizar-repo/calcs"
          - "@nizar-repo/error-handler"
          - "@nizar-repo/eslint-config"
          - "@nizar-repo/typescript-config"
          - "@nizar-repo/ui"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
      - run: yarn --force
      - run: yarn set:auth ${{github.event.inputs.package_name}} ${{secrets.NPM_PUBLISH_TOKEN}}
      - run: yarn build:package ${{github.event.inputs.package_name}}
      - run: yarn --force
      - run: yarn publish-package ${{github.event.inputs.package_name}}
      - run: echo "Publishing ${{github.event.inputs.package_name}} with token ${{secrets.NPM_PUBLISH_TOKEN}}"
