name: Tag Branch
on:
  workflow_dispatch:

jobs:
  tag-workflow:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
            node-version: 20
      - name: Extract version
        run: |
          echo "app_version=$(cd "$(node scripts/lib/getPackageLocation.js @nizar-repo/error-handler)" && cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
        id: version
      - name: Use the version
        run: echo "The version is ${{ steps.version.outputs.app_version }}"
      - name: Check curr directory
        run: |
          echo "$(cat package.json | jq -r '.name')"
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.64.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: false
      #     CUSTOM_TAG: "@nizar-repo/error-handler/v${{ steps.version.outputs.app_version }}"
  # release:
  #   needs: tag_workflow
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   permissions: write-all
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: "0"
  #     - name: Extract version
  #       run: |
  #         echo "app_version=$(npm pkg -w @nizar-repo/error-handler get version | head -n 1 | xargs)" >> $GITHUB_OUTPUT
  #       id: version
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: "@nizar-repo/error-handler/v${{ steps.version.outputs.app_version }}"
  #         release_name: "Release @nizar-repo/error-handler/v${{ steps.version.outputs.app_version }}"
  #         body: |
  #           # Important Urls:
  #           - `Microservice:` path
  #           - `Package:` path
  #         draft: false
  #         prerelease: false
