name: Bump version
on:
  workflow_dispatch:

jobs:
  tag_workflow:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Extract version
        run: |
          echo "app_version=$(npm pkg -w @nizar-repo/error-handler get version | head -n 1 | xargs)" >> $GITHUB_OUTPUT
        id: version
      - name: Use the version
        run: echo "The version is ${{ steps.version.outputs.app_version }}"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          CUSTOM_TAG: "@testing_tag/v1.1.1"
  release:
    needs: tag_workflow
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Extract version
        run: |
          echo "app_version=$(npm pkg -w @nizar-repo/error-handler get version | head -n 1 | xargs)" >> $GITHUB_OUTPUT
        id: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "@testing_tag/v1.1.1"
          release_name: "Release @testing_tag/v1.1.1"
          body: |
            Important Urls:
            - Microservice
            - Package
            draft: false
            prerelease: false
