on:
  workflow_call:
    inputs:
      package_name:
        type: string
        required: true



jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Extract version
            run: |
              echo "app_version=$(cd "$(node scripts/lib/getPackageLocation.js ${{inputs.package_name}})" && cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
            id: version
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
            with:
              tag_name: "${{inputs.package_name}}/v${{ steps.version.outputs.app_version }}"
              release_name: "Release ${{inputs.package_name}}/v${{ steps.version.outputs.app_version }}"
              body: |
                Important Urls:
                - Microservice
                - Package
              draft: false
              prerelease: false