
on:
  workflow_call:
    inputs:
      package_name:
        type: string
        required: true

jobs:
  set-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Extract version
        run: |
          echo "app_version=$(cd "$(node scripts/lib/getPackageLocation.js ${{inputs.package_name}})" && cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
        id: version

      - name: Use the version
        run: echo "The version is ${{ steps.version.outputs.app_version }}"

      - name: Display correct
        run : echo "this is correct"
        if: ${{inputs.package_name}} == "@nizar-repo/error-handler"
      - name: Display Wrong
        run : echo "this is Wrong"
        if: ${{inputs.package_name}} != "-handler"
      - name: Shouldn't Display
        run : echo "this is Wrong"
        if: ${{inputs.package_name}} == "-handler"
